name: 'Install macOS Dependencies'
description: 'Installs macOS GTK and Python Dependencies'
inputs:
  gtk_version:
    description: 'GTK version'
    default: '4'
runs:
  using: composite
  steps:
    - if: inputs.gtk_version == '3'
      run: brew install gtk+3 gtksourceview4 gtk-mac-integration
      shell: bash
    - if: inputs.gtk_version == '4'
      run:  brew install gtk4 gtksourceview5 libadwaita adwaita-icon-theme
      shell: bash
    - run:  brew install gobject-introspection graphviz create-dmg upx
      shell: bash
